site_name: LSP for Sublime Text
repo_url: https://github.com/sublimelsp/LSP/
edit_uri: edit/st4000-exploration/docs/

theme:
  name: material
  palette:
      scheme: slate
      accent: orange
      primary: orange

  icon:
    logo: fontawesome/solid/book-open

# override css
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # tabs for ST4 and ST3 content
  - pymdownx.tabbed

  # higlight code block
  - pymdownx.highlight
  - pymdownx.superfences

  # add tip, warning info boxes
  - admonition

  # show # after each header
  - toc:
      permalink: '#'

nav:
  - Getting Started: './index.md'
  - Setup Language Server: './setup_language_server.md'
  - Features:
    - './features/overview.md'
    - './features/keybindings.md'
    - './features/command_palette.md'
    - './features/settings.md'
  - Guides:
    - './guide/client_configuration.md'
    - './guide/create_plugin.md'
  - Common Issues: './common_issues.md'
